# Change these first
owner: chminc # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Website
    url: https://chminc.in
    __dangerous__insecure: true
  - name: cPortal
    url: https://chminc.co.in
  - name: DECP1
    url: https://decp1.6dns.net
  - name: DEWI1
    check: "tcp-ping"
    url: dewi1.6dns.net
    port: 3389
  - name: LUDA1
    url: https://luda1.6dns.net
    __dangerous__insecure: true
  - name: LUDA2
    url: https://luda2.6dns.net
  - name: Cloud
    url: https://cloud.6dns.net

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.chminc.support
  # baseUrl: /your-repo-name
  #themeUrl: https://status.chminc.support/my-custom-theme.css
  theme: ocean
  logoUrl: https://chminc.in/wp-content/uploads/2022/03/logo.png
  favicon: https://chminc.in/wp-content/uploads/2022/03/favicon-chminc.co_.in_.png
  name: CHM, Inc. Status
  introTitle: "**Welcome** to CHM, Inc.'s real-time and historical data on system performance."
  introMessage: Our infrastructure status. [**Get Help from here**](https://chminc.support)
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://chmorg.com
    - title: Help Center
      href: https://chminc.support

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: This page refresh every 5 minutes. Crafted with ❤ by [CHM, Inc.](https://chmorg.com)
